version: "3.8"

services:
    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile.frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend

    admin:
        build:
            context: ../admin
            dockerfile: Dockerfile.admin
        ports:
            - "3001:3000"
        depends_on:
            - backend

    backend:
        build:
            context: ../backend
            dockerfile: Dockerfile.backend
        ports:
            - "5000:5000"
        environment:
            - MONGODB_URI=mongodb://mongodb:27017/restaurant
        depends_on:
            - mongodb

    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
